apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2
    app.kubernetes.io/part-of: basic-app
  name: devfile-sample-2
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/christianvogt-tenant/basic-app/devfile-sample-2@sha256:7bb962e1a3f650228b09711bc598aee54d567f0c169bf257f32ee70a6a2e9bdb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
