apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qv8b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qv8b
    app.kubernetes.io/part-of: basic-app
  name: devfile-sample-qv8b
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qv8b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qv8b
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/christianvogt-tenant/basic-app/devfile-sample-qv8b@sha256:f841bc0760423e3533c0b1b1fdb9bc64aa53cf3294d9d21ee29a8301569b4b32
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
