apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qv8b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qv8b
    app.kubernetes.io/part-of: basic-app
  name: devfile-sample-qv8b
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-qv8b
status:
  loadBalancer: {}
