apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qv8b
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/christianvogt-tenant/basic-app/devfile-sample-qv8b@sha256:a69c143582cbc38c0585d495c4bf9279ed5e65182e261b2fe6891f9298a4b2c2
        name: my-nodejs
        resources: {}
status: {}
